version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: nexhr_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nexhr_redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  backend:
    build: .
    container_name: nexhr_backend
    restart: always
    command: gunicorn nexhr_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DOCKERIZED: 1   # ✅ force settings.py into Docker mode
    depends_on:
      - postgres
      - redis

  celery:
    build: .
    container_name: nexhr_celery
    restart: always
    command: celery -A nexhr_backend worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DOCKERIZED: 1
    depends_on:
      - redis
      - backend

  celery-beat:
    build: .
    container_name: nexhr_celery_beat
    restart: always
    command: celery -A nexhr_backend beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DOCKERIZED: 1
    depends_on:
      - redis
      - backend

  flower:
    image: mher/flower:latest
    container_name: nexhr_flower
    restart: always
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery

volumes:
  postgres_data:
