version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: nexhr_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  celery:
    build: .
    container_name: nexhr_celery
    command: celery -A nexhr_backend worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - DOCKERIZED=1
    depends_on:
      - redis

  flower:
    image: mher/flower:latest
    container_name: nexhr_flower
    command: ["celery", "--broker=redis://redis:6379/0", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
