# Generated by Django 5.2 on 2025-09-21 16:23

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('candidate_fname', models.CharField(max_length=255)),
                ('candidate_lname', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('profile_embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('skills_coverage', models.FloatField(blank=True, null=True)),
                ('experience_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('screening_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('years_of_experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('previous_job_titles', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('education_level', models.CharField(max_length=100)),
                ('institution_name', models.CharField(max_length=255)),
                ('degree_detail', models.CharField(max_length=255)),
                ('grades', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='recruitment.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('location_type', models.CharField(max_length=50)),
                ('job_deadline', models.DateTimeField()),
                ('location', models.TextField(blank=True)),
                ('city', models.CharField(default='N/A', max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='N/A', max_length=100, null=True)),
                ('salary_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('period', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(max_length=50)),
                ('experience_level', models.IntegerField()),
                ('description_embedding', pgvector.django.vector.VectorField(dimensions=768, null=True)),
                ('job_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.department')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('required_skills', models.ManyToManyField(related_name='jobs', to='recruitment.requiredskill')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobdetails'),
        ),
    ]
