# Generated by Django 5.2 on 2025-08-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience_level',
            field=models.IntegerField(),
        ),
    ]
