# Generated by Django 5.2 on 2025-08-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_jobdetails_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_url',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
