# Generated by Django 5.2 on 2025-08-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_remove_jobapplication_resume_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='screening_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='skills_coverage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
