# Generated by Django 5.2 on 2025-05-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='job_category',
        ),
    ]
