# Generated by Django 5.2 on 2025-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_jobdetails_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='city',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='country',
            field=models.CharField(default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
