# Generated by Django 5.2 on 2025-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylinkedinauth',
            name='id_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylinkedinauth',
            name='person_urn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companylinkedinauth',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companylinkedinauth',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
