# Generated by Django 5.2 on 2025-09-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('FINANCE', 'Finance'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='FINANCE', max_length=20),
        ),
    ]
