# Generated by Django 5.2 on 2025-09-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_gross_salary_alter_payroll_net_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
    ]
