# Generated by Django 5.2 on 2025-09-17 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_statutorydeduction_taxbracket_remove_payroll_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='approval_status',
            field=models.CharField(choices=[('AWAITING', 'Awaiting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='AWAITING', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payslip_pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
